<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core1.proto

namespace Corerq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>corerq.CoreRequest</code>
 */
class CoreRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core1::initOnce();
        parent::__construct($data);
    }

}

