<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core1.proto

namespace Corerq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>corerq.ParamScruttinAll</code>
 */
class ParamScruttinAll extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string fecha = 1;</code>
     */
    protected $fecha = '';
    /**
     * Generated from protobuf field <code>string codeclient = 2;</code>
     */
    protected $codeclient = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $fecha
     *     @type string $codeclient
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string fecha = 1;</code>
     * @return string
     */
    public function getFecha()
    {
        return $this->fecha;
    }

    /**
     * Generated from protobuf field <code>string fecha = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFecha($var)
    {
        GPBUtil::checkString($var, True);
        $this->fecha = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string codeclient = 2;</code>
     * @return string
     */
    public function getCodeclient()
    {
        return $this->codeclient;
    }

    /**
     * Generated from protobuf field <code>string codeclient = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeclient($var)
    {
        GPBUtil::checkString($var, True);
        $this->codeclient = $var;

        return $this;
    }

}

