<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core1.proto

namespace Corerq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>corerq.ParambySerial</code>
 */
class ParambySerial extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 thisSerial = 1;</code>
     */
    protected $thisSerial = 0;
    /**
     * Generated from protobuf field <code>string codeclient = 2;</code>
     */
    protected $codeclient = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $thisSerial
     *     @type string $codeclient
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 thisSerial = 1;</code>
     * @return int|string
     */
    public function getThisSerial()
    {
        return $this->thisSerial;
    }

    /**
     * Generated from protobuf field <code>int64 thisSerial = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setThisSerial($var)
    {
        GPBUtil::checkInt64($var);
        $this->thisSerial = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string codeclient = 2;</code>
     * @return string
     */
    public function getCodeclient()
    {
        return $this->codeclient;
    }

    /**
     * Generated from protobuf field <code>string codeclient = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeclient($var)
    {
        GPBUtil::checkString($var, True);
        $this->codeclient = $var;

        return $this;
    }

}

