<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core1.proto

namespace Corerq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>corerq.StateOne</code>
 */
class StateOne extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 state = 1;</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>string resolve = 2;</code>
     */
    protected $resolve = '';
    /**
     * Generated from protobuf field <code>double pay = 3;</code>
     */
    protected $pay = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $state
     *     @type string $resolve
     *     @type float $pay
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 state = 1;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>int32 state = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkInt32($var);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string resolve = 2;</code>
     * @return string
     */
    public function getResolve()
    {
        return $this->resolve;
    }

    /**
     * Generated from protobuf field <code>string resolve = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResolve($var)
    {
        GPBUtil::checkString($var, True);
        $this->resolve = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double pay = 3;</code>
     * @return float
     */
    public function getPay()
    {
        return $this->pay;
    }

    /**
     * Generated from protobuf field <code>double pay = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPay($var)
    {
        GPBUtil::checkDouble($var);
        $this->pay = $var;

        return $this;
    }

}

