<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core1.proto

namespace Corerq;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>corerq.StateAll</code>
 */
class StateAll extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool state = 1;</code>
     */
    protected $state = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $state
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core1::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool state = 1;</code>
     * @return bool
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>bool state = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkBool($var);
        $this->state = $var;

        return $this;
    }

}

