<?

$CODE_FOR_PAY = "PAY";
$CODE_FOR_PAY_RECARD = "PAY_RECARD";

$CODE_FOR_STATUS = "STATUS";
$CODE_FOR_STATUS_RECARD = "STATUS_RECARD";

$CODE_FOR_CREATE_CLIENT = "CREATE_CLIENT";
$CODE_FOR_CREATE_CLIENT_WITHPAY = "CREATE_CLIENT_WITHOUTPAY";
$CODE_FOR_SEND_CREDENTIAL = "CREDENTIAL_SEND";
$CODE_FOR_REQUEST_TOKET = "REQUEST_TOKET";
$CODE_FOR_RESPONSE_TOKET = "RESPONSE_TOKET";
$CODE_FOR_CREATE_USER = "CREATE_USER_DEFAULT";
$TEST_CODE_FOR_STATUS = "TEST_STATUS";
$TEST_CODE_FOR_PAY = "TEST_PAY";
